"""Search task — query SearXNG and dispatch article ingestion."""
import json
import logging
import os
from datetime import datetime, timezone, timedelta

import httpx
import redis as redis_lib
from sqlalchemy import select

from worker.celeryconfig import app
from worker.rls import with_rls_context
from app.models import Topic

logger = logging.getLogger(__name__)

_searxng_url = os.environ.get("SEARXNG_URL", "http://searxng:8080")
_http = httpx.Client(timeout=httpx.Timeout(30.0, connect=10.0))

# Sync Redis for search status tracking + pub/sub (mirrors _alert_redis in price_alerts.py)
_search_redis = redis_lib.from_url(
    os.environ.get("REDIS_CACHE_URL", "redis://redis:6379/3")
)


@app.task(name="run_topic_search")
@with_rls_context
def run_topic_search(user_id: str, topic_id: str, session=None):
    """Fetch LLM-generated search queries from topic config, call SearXNG, dispatch ingestion.

    Uses queries from topic.config["search_queries"] (generated by generate_search_queries)
    plus any user-configured search_terms. If no generated queries exist yet, dispatches
    generate_search_queries first and returns early.

    Deduplicates URLs within the batch before dispatching ingest_article.
    """
    status_key = f"ttwatch:search_status:{topic_id}"

    topic = session.execute(
        select(Topic).where(Topic.id == topic_id)
    ).scalar_one_or_none()

    if not topic:
        logger.warning(f"Topic {topic_id} not found for user {user_id}")
        return {"status": "topic_not_found"}

    # Use LLM-generated search queries instead of raw topic name
    config = topic.config or {}
    search_queries = config.get("search_queries", [])

    if not search_queries:
        # No generated queries yet — trigger generation (which will re-dispatch us)
        logger.info(
            f"No search_queries for topic '{topic.name}', "
            "dispatching generate_search_queries first"
        )
        app.send_task(
            "generate_search_queries", args=[user_id, topic_id]
        )
        return {"status": "pending_query_generation"}

    # Preserve started_at from earlier phases (generating_queries)
    started_at = datetime.now(timezone.utc).isoformat()
    try:
        prev_started = _search_redis.get(f"ttwatch:search_progress:{topic_id}:started_at")
        if prev_started:
            started_at = prev_started.decode()
    except Exception:
        pass

    # Set search status to "searching"
    try:
        _search_redis.setex(status_key, 3600, json.dumps({
            "status": "searching",
            "started_at": started_at,
            "user_id": user_id,
        }))
        _search_redis.setex(
            f"ttwatch:search_progress:{topic_id}:started_at", 7200, started_at
        )
    except Exception as e:
        logger.warning(f"Failed to set search status: {e}")

    try:
        # Start with LLM-generated queries
        queries = list(search_queries)

        # Also include any user-configured additional search terms
        search_terms = config.get("search_terms", [])
        if isinstance(search_terms, list):
            for term in search_terms:
                if isinstance(term, str) and term.strip():
                    queries.append(term.strip())

        # Set query counters for progress tracking
        progress_prefix = f"ttwatch:search_progress:{topic_id}"
        try:
            _search_redis.set(f"{progress_prefix}:queries_total", len(queries), ex=7200)
            _search_redis.set(f"{progress_prefix}:queries_completed", 0, ex=7200)
        except Exception:
            pass

        # Collect all results, deduplicate by URL within this batch
        seen_urls = set()
        results = []

        for query in queries:
            try:
                resp = _http.get(
                    f"{_searxng_url}/search",
                    params={"q": query, "format": "json"},
                )
                resp.raise_for_status()
                data = resp.json()
            except Exception as e:
                logger.error(f"SearXNG search failed for query '{query}': {e}")
                try:
                    _search_redis.incr(f"{progress_prefix}:queries_completed")
                except Exception:
                    pass
                continue

            # Track per-query progress
            try:
                _search_redis.incr(f"{progress_prefix}:queries_completed")
            except Exception:
                pass

            for item in data.get("results", []):
                url = item.get("url", "").strip()
                if not url or url in seen_urls:
                    continue
                seen_urls.add(url)
                results.append({
                    "url": url,
                    "title": item.get("title", ""),
                    "source_name": item.get("engine", ""),
                    "source_url": item.get("parsed_url", [""])[0] if item.get("parsed_url") else "",
                })

        # Dispatch ingestion for each unique result
        for r in results:
            app.send_task("ingest_article", args=[
                user_id,
                topic_id,
                r["url"],
            ], kwargs={
                "title": r["title"],
                "source_name": r["source_name"],
                "source_url": r["source_url"],
            })

        # Track expected article count for processing progress
        dispatched_count = len(results)
        if dispatched_count > 0:
            try:
                proc_prefix = f"ttwatch:processing:{topic_id}"
                _search_redis.set(f"{proc_prefix}:expected", dispatched_count, ex=7200)
                _search_redis.set(f"{proc_prefix}:phase", "ingesting", ex=7200)
                # Reset counters for new batch
                for counter in ("embedded", "summarized", "sentiment", "relevance", "entities"):
                    _search_redis.delete(f"{proc_prefix}:{counter}")
                _search_redis.delete(f"{proc_prefix}:cluster_dispatched")
                # Reset aggregate progress counters
                _search_redis.set(f"{progress_prefix}:ingested", 0, ex=7200)
                _search_redis.set(f"{progress_prefix}:tasks_completed", 0, ex=7200)
            except Exception as e:
                logger.warning(f"Failed to set processing counters: {e}")

        logger.info(
            f"run_topic_search: dispatched {len(results)} articles "
            f"for topic '{topic.name}' ({len(queries)} queries)"
        )

        if dispatched_count == 0:
            # No articles found — mark as completed immediately
            completed_payload = {
                "status": "completed",
                "completed_at": datetime.now(timezone.utc).isoformat(),
                "articles_found": 0,
                "started_at": started_at,
                "user_id": user_id,
            }
            try:
                _search_redis.setex(status_key, 3600, json.dumps(completed_payload))
                _search_redis.publish("ttwatch:search:completed", json.dumps({
                    **completed_payload,
                    "type": "search_completed",
                    "topic_id": topic_id,
                }))
            except Exception as e:
                logger.warning(f"Failed to set search completed status: {e}")
        else:
            # Transition to "processing" — NOT "completed" (processing hasn't started yet)
            processing_payload = {
                "status": "processing",
                "started_at": started_at,
                "articles_found": dispatched_count,
                "user_id": user_id,
            }
            try:
                _search_redis.setex(status_key, 3600, json.dumps(processing_payload))
                _search_redis.publish("ttwatch:search:progress", json.dumps({
                    **processing_payload,
                    "type": "search_progress",
                    "topic_id": topic_id,
                }))
            except Exception as e:
                logger.warning(f"Failed to set processing status: {e}")

        return {"status": "ok", "dispatched": len(results)}

    except Exception as e:
        logger.error(f"run_topic_search failed for topic {topic_id}: {e}")
        try:
            _search_redis.setex(status_key, 3600, json.dumps({
                "status": "error",
                "error": str(e),
                "user_id": user_id,
            }))
        except Exception:
            pass
        raise


_STALL_TIMEOUT = timedelta(minutes=5)


@app.task(name="detect_stalled_pipelines")
def detect_stalled_pipelines():
    """Safety net: detect and force-complete pipelines stuck at 'processing'.

    Scans all ttwatch:search_status:* keys. If a pipeline has been in
    'processing' status for over 5 minutes, forces the phase to 'complete'
    and triggers recluster_topic so the frontend gets an update.
    """
    now = datetime.now(timezone.utc)
    unstuck = 0

    try:
        for key in _search_redis.scan_iter("ttwatch:search_status:*"):
            raw = _search_redis.get(key)
            if not raw:
                continue
            try:
                data = json.loads(raw)
            except (json.JSONDecodeError, TypeError):
                continue

            if data.get("status") != "processing":
                continue

            started_at_str = data.get("started_at")
            if not started_at_str:
                continue

            try:
                started_at = datetime.fromisoformat(started_at_str)
            except (ValueError, TypeError):
                continue

            if now - started_at < _STALL_TIMEOUT:
                continue

            # Pipeline is stalled — extract topic_id from key
            topic_id = key.decode().split(":")[-1] if isinstance(key, bytes) else key.split(":")[-1]
            user_id = data.get("user_id", "")

            # Force phase to complete
            proc_prefix = f"ttwatch:processing:{topic_id}"
            current_phase_raw = _search_redis.get(f"{proc_prefix}:phase")
            current_phase = current_phase_raw.decode() if current_phase_raw else ""

            if current_phase == "clustering":
                continue  # Clustering in progress

            if current_phase == "complete":
                # Phase completed but search_status stuck at "processing" — finalize it
                completed_payload = {
                    "status": "completed",
                    "completed_at": now.isoformat(),
                    "started_at": started_at_str,
                    "articles_found": data.get("articles_found", 0),
                    "user_id": user_id,
                }
                _search_redis.setex(key, 3600, json.dumps(completed_payload))
                _search_redis.publish("ttwatch:search:completed", json.dumps({
                    **completed_payload,
                    "type": "search_completed",
                    "topic_id": topic_id,
                }))
                logger.info(f"Finalized stale search_status for topic {topic_id} (phase was already complete)")
                unstuck += 1
                continue

            logger.warning(
                f"Stall detected for topic {topic_id}: status='processing' "
                f"since {started_at_str}, phase='{current_phase}'. Forcing completion."
            )

            # Dispatch recluster if not already dispatched
            lock_key = f"{proc_prefix}:cluster_dispatched"
            if _search_redis.set(lock_key, "1", nx=True, ex=7200):
                app.send_task("recluster_topic", args=[user_id, topic_id])
                _search_redis.set(f"{proc_prefix}:phase", "clustering", ex=7200)
                logger.info(f"Force-dispatched recluster_topic for stalled topic {topic_id}")
            else:
                # Clustering was already dispatched but didn't complete — force complete
                _search_redis.set(f"{proc_prefix}:phase", "complete", ex=7200)
                completed_payload = {
                    "status": "completed",
                    "completed_at": now.isoformat(),
                    "started_at": started_at_str,
                    "articles_found": data.get("articles_found", 0),
                    "user_id": user_id,
                }
                _search_redis.setex(key, 3600, json.dumps(completed_payload))
                _search_redis.publish("ttwatch:search:completed", json.dumps({
                    **completed_payload,
                    "type": "search_completed",
                    "topic_id": topic_id,
                }))

            unstuck += 1

    except Exception as e:
        logger.error(f"detect_stalled_pipelines failed: {e}")

    if unstuck:
        logger.info(f"detect_stalled_pipelines: unstuck {unstuck} pipeline(s)")
    return {"unstuck": unstuck}
